name: Angular - Create Component - Stable

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:latest
    env:
      HOME: /home/bituser
    steps:
      - name: Show BVM config
        run: |
          bvm config
      - name: Create a new workspace
        run: |
          bit new angular my-workspace --env teambit.angular/angular --default-scope my-org.my-scope --log error
      - name: Create a React component and set env
        run: |
          cd my-workspace
          bit create ng-module pages/welcome --env my-org.my-scope/envs/my-angular-env --log error
      - name: Install dependencies
        run: |
          cd my-workspace
          bit install --add-missing-deps --log error
      - name: Show components, envs and status
        run: |
          cd my-workspace
          bit status --log error
          bit envs --log error
      - name: Compile, lint, test components
        run: |
          cd my-workspace
          bit compile --log error
          bit lint --log error
          bit test --log error
      - name: Preview components
        run: |
          cd my-workspace
          bit start --log error &
          checkserver http://localhost:3000
      - name: Tag components
        run: |
          cd my-workspace
          bit tag --message "initial tag" --log error
      - name: Create a local scope
        run: |
          barescope my-org.my-scope my-workspace
      - name: Export components
        run: |
          cd my-workspace
          bit export --log error
    continue-on-error: false
