name: Angular - Create App - Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/nightly:latest
    env:
      HOME: /home/bituser
    steps:
      - name: Show BVM config
        run: |
          bvm config
      - name: Initialize a new workspace
        run: |
          bit init my-workspace --default-scope my-org.my-scope --log error
      - name: Create a Angular app component
        run: |
          cd my-workspace
          bit create ng-app apps/my-app --aspect teambit.angular/angular --log error
          bit use apps/my-app --log error
      - name: Install dependencies
        run: |
          cd my-workspace
          bit install --add-missing-deps --log error
      - name: Show components, envs and status
        run: |
          cd my-workspace
          bit status --log error
          bit envs --log error
      - name: Compile, lint, test components
        run: |
          cd my-workspace
          bit compile --log error
          bit lint --log error
          bit test --log error
      - name: Run Angular app component
        run: |
          cd my-workspace
          bit run my-app --log error &
          checkserver http://localhost:3000
      - name: Preview components
        run: |
          cd my-workspace
          bit start --log error &
          checkserver http://localhost:3000
      - name: Tag components
        run: |
          cd my-workspace
          bit tag --message "initial tag" --log error
      - name: Create a local scope
        run: |
          barescope my-org.my-scope my-workspace
      - name: Export components
        run: |
          cd my-workspace
          bit export --log error
    continue-on-error: false
