name: Next.js - Quickstart - Empty

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: bitsrc/stable:latest
    env:
      HOME: /home/bituser

    steps:
      - name: Show BVM config
        run: |
          bvm config
      - name: Initialize a workspace
        run: |
          bit new hello-world-nextjs my-hello-world-nextjs --env frontend.nextjs/templates/community-starters/hello-world-nextjs --empty --log error
      - name: Show component details
        run: |
          cd my-hello-world-nextjs
          bit list
          bit envs
      - name: Preview components
        run: |
          cd my-hello-world-nextjs
          bit start &
          checkserver http://localhost:3000
      - name: Collaborate
        run: |
          cd my-hello-world-nextjs
          bit status
      - name: Create a local scope, compile and export
        run: |
          barescope my-org.my-scope-name my-hello-world-nextjs
          cd my-hello-world-nextjs
          bit scope rename my-org.my-scope my-org.my-scope-name --refactor
          bit link
          bit compile
          bit tag --message "initial tag"
          bit export
    continue-on-error: false
