name: Vue env - Default Starter (nightly)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: bitsrc/nightly:latest
    env:
      HOME: /home/bituser
        
    steps:
    - name: Initialize a workspace
      run: |
        bvm config set RELEASE_TYPE nightly
        bvm config
        bvm versions
        bvm upgrade
        bit --version
        bit new vue my-vue-workspace --env bitdev.vue/vue-env
    - name: Check initial status
      run: |
        cd my-vue-workspace
        bit list
        bit status
        bit templates
    - name: Create a new component
      run: |
        cd my-vue-workspace
        bit create vue ui/my-first
        bit install
        bit list
        bit status
        bit start &
        checkserver http://localhost:3000
    - name: Create a new app
      run: |
        cd my-vue-workspace
        bit create vue-app apps/my-second
        bit install
        bit list
        # bit use apps/my-second
        bit app list
        bit status
        bit run my-second-app &
        checkserver http://localhost:3000
    - name: Lint and test
      run: |
        cd my-vue-workspace
        bit list
        bit status
        bit lint
        bit test
    - name: Create a local scope, compile and export
      run: |
        barescope my-org.my-scope-name my-vue-workspace
        cd my-vue-workspace
        bit scope rename org.scope-name my-org.my-scope-name --refactor
        bit link
        bit compile
        bit tag --message "initial tag"
        bit export
    continue-on-error: false
